spring:
  application:
     name: produtos API
  datasource:
    url: jdbc:h2:mem:produtos   //conexão p propriedade:memoria:nomeDoBanco
    username: bb
    password: 2004

  jpa:
    database-platform: org.hibernate.dialect.H2dialect
  h2:
    console:
      enabled: true
      path: /h2-console